#!/bin/bash

FILES_DIR=../files
## A copy of the FILES_DIR folder is here: /projects/MRC-IEU/research/projects/ieu1/wp2/004/working/data/data-files-for-ewascatalog2

RUNNING_DIR=../running
## Base directory of the website directory

## Database settings can be found in the settings.env file
##   /projects/MRC-IEU/research/projects/ieu1/wp2/004/working/scripts/ewascatalog2/settings.env
SETTINGS=../settings.env

CMD="$1"

USER_ID=`id -u`
GROUP_ID=`id -g`
DOCKER_COMPOSE="FILES_DIR=${FILES_DIR} USER_ID=${USER_ID} GROUP_ID=${GROUP_ID} docker-compose"

install_website() {
    bash website/install.sh ${RUNNING_DIR} ${FILES_DIR} ${SETTINGS}
}
copy_webserver() {
    cp -r webserver ${RUNNING_DIR}
}
copy_docker() {
    cp docker/*.yml ${RUNNING_DIR}
}
build_catalog() {
    mkdir -p ${RUNNING_DIR}
    cp ${SETTINGS} ${RUNNING_DIR}
    install_website
    copy_docker
    copy_webserver
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} build"
}
start_catalog() {
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} up -d"
}
create_database() {
    cp -r database ${RUNNING_DIR}
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} exec db bash -c 'cd /code; bash create-annotations.sh /files'"
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} exec db bash -c 'cd /code; bash create.sh ../settings.env /files'"
}
update_website() {
    install_website
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} restart web"
}
update_webserver() {
    cp -r webserver ${RUNNING_DIR}
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} stop nginx"
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} build nginx"
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} start nginx"
}
update_database() {
    base_dir=`pwd`
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} exec db bash -c 'cd /code; bash generate-zenodo-doi.sh ../settings.env /files'"
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} exec db bash -c 'cd /code; bash add-to-ewas.sh ../settings.env /files'"
    cd $base_dir; update_website
}
prep_inhouse_data() {
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} exec db bash -c 'cd /code; bash prep-inhouse-data.sh ../settings.env /files'"
}
check_new_upload() {
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} exec db bash -c 'cd /code; bash prep-new-data.sh ../settings.env /files'"
}
stop_catalog() {
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} stop"
}
delete_catalog() {
    cd ${RUNNING_DIR}; eval "${DOCKER_COMPOSE} rm"
}


if [ ${CMD} = "build" ]; then
    build_catalog
elif [ ${CMD} = "start" ]; then
    start_catalog
elif [ ${CMD} = "create-database" ]; then
    create_database
elif [ ${CMD} = "update-website" ]; then
    update_website
elif [ ${CMD} = "update-webserver" ]; then
    update_webserver
elif [ ${CMD} = "update-database" ]; then
    update_database
elif [ ${CMD} = "prep-inhouse-data" ]; then
    prep_inhouse_data
elif [ ${CMD} = "check-new-upload" ]; then
    check_new_upload
elif [ ${CMD} = "stop" ]; then
    stop_catalog
elif [ ${CMD} = "rm" ]; then
    delete_catalog
elif [ ${CMD} = "all" ]; then
    build_catalog
    start_catalog
    create_database
else
cat <<EOF
Error: Invalid command

Usage: 
    catalog CMD
where CMD is one of the following:
    build:            build the catalog docker container
    start:            start the catalog running
    create-database:  construct the catalog database
    update-website:   copy the website files and restart the website
    update-database:  add associations to the database
    update-webserver: copy the webserver files and restart webserver
    stop:             stop the catalog
    rm:               delete catalog container
    all:              build->start->create-database
EOF
fi

## to delete *all* docker containers and images:
##    docker system prune -a
